# Generated by Django 3.2.12 on 2022-12-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий СУП УК'),
        ),
        migrations.AlterField(
            model_name='card',
            name='send',
            field=models.BooleanField(default=False, verbose_name='Выбрать все'),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Последнее обновление'),
        ),
    ]
