# Generated by Django 3.2.16 on 2022-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0002_auto_20221221_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(verbose_name='Последнее обновление')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Согласован'), (1, 'Согласование СУП'), (2, 'На доработке'), (3, 'Новый')], default=3, verbose_name='Статус')),
                ('send', models.BooleanField(default=False, verbose_name='Выбрать все')),
                ('name_of_user', models.TextField(verbose_name='ФИО пользователя')),
                ('organization', models.CharField(max_length=300, verbose_name='Организация')),
                ('role', models.CharField(max_length=1000, verbose_name='Должность')),
                ('fio', models.CharField(max_length=1000, verbose_name='ФИО сотрудника, в чью карту устанавливается КПЭ')),
                ('id_kpi', models.CharField(default='-', max_length=300, verbose_name='Идентификатор КПЭ')),
                ('type', models.CharField(default='-', max_length=100, verbose_name='КПЭ/КлС')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование КПЭ / КлС')),
                ('method', models.CharField(max_length=1000, verbose_name='Методика расчета')),
                ('low_level', models.CharField(max_length=3000, verbose_name='Нижний уровень')),
                ('target_level', models.CharField(max_length=3000, verbose_name='Целевой уровень')),
                ('high_level', models.CharField(max_length=3000, verbose_name='Верхний уровень')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('first_quarter', models.CharField(blank=True, max_length=1000, verbose_name='Прогноз 1 кв')),
                ('second_quarter', models.CharField(blank=True, max_length=1000, verbose_name='Прогноз 2 кв')),
                ('third_quarter', models.CharField(blank=True, max_length=1000, verbose_name='Прогноз 3 кв')),
                ('fourth_quarter', models.CharField(blank=True, max_length=1000, verbose_name='Прогноз 4 кв')),
                ('reason', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Причина отклонения')),
                ('measure', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Предпринимаемые меры')),
                ('forecast', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Прогнозное значение')),
                ('verificator', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Верификатор')),
                ('delete', models.BooleanField(default=0)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий СУП УК')),
            ],
            options={
                'db_table': 'cardlog',
                'managed': True,
            },
        ),
    ]