# Generated by Django 3.2.16 on 2023-01-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0003_cardlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='forecast',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Прогнозируемый результат после реализации мероприятий'),
        ),
        migrations.AlterField(
            model_name='card',
            name='measure',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Мероприятия по снижению риска невыполнения'),
        ),
        migrations.AlterField(
            model_name='card',
            name='method',
            field=models.CharField(max_length=1000, verbose_name='Тип КПЭ/КлС'),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='forecast',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Прогнозируемый результат после реализации мероприятий'),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='measure',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Мероприятия по снижению риска невыполнения'),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='method',
            field=models.CharField(max_length=1000, verbose_name='Тип КПЭ/КлС'),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='weight',
            field=models.IntegerField(verbose_name='Вес КПЭ/Знаичмость КлС'),
        ),
    ]
