# Generated by Django 3.2.16 on 2023-01-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0004_auto_20230119_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='weight',
            field=models.IntegerField(verbose_name='Вес КПЭ/Знаичмость КлС'),
        ),
    ]
