# Generated by Django 3.2.16 on 2023-01-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0005_alter_card_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlog',
            name='name_of_user',
            field=models.TextField(blank=True, verbose_name='ФИО пользователя'),
        ),
    ]
